<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
       <link type="text/css" rel="stylesheet" href="css/style.css">
       <script src="js/ajouter.js"></script>
        <title> Lire Absence </title>
    </head>
    <body>
        
  
    </body>
</html>